name: Network test
on:
  workflow_dispatch:
jobs:
  network-test:
    runs-on: ubuntu-latest
    name: Test network
    timeout-minutes: 90
    steps:
      - uses: docker://getsentry/craft:latest
        name: Test pypi network connection
        with:
          entrypoint: /bin/bash
          args: >-
            -e
            -c "
            set -x &&
            apt-get update && apt-get install dnsutils traceroute curl &&
            dig pypi.org A;
            dig pypi.org AAAA;
            dig files.pythonhosted.org A;
            dig files.pythonhosted.org AAAA;
            traceroute pypi.org;
            traceroute files.pythonhosted.org;
            curl -vvv -I --ipv4 https://pypi.org/pypi/pip/json;
            curl -vvv -I --ipv4 https://files.pythonhosted.org/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz;
            echo -n | openssl s_client -4 -connect pypi.org:443;
            echo -n | openssl s_client -4 -connect files.pythonhosted.org:443;
            "
